shinyTemplate <-
'# Generated by ShinyGenerator v0.0.1
# Please edit background and other relevant sections

# load packages ----
#PACKAGES#

# read results from data folder ----
#READ#

# ui shiny ----
ui <- dashboardPage(
  dashboardHeader(title = "Menu"),
  ## menu ----
  dashboardSidebar(
    sidebarMenu(
      #MENU#
    )
  ),
  ## body ----
  dashboardBody(
    tabItems(
      #BODY#
    )
  )
)

# server shiny ----
server <- function(input, output, session) {
#SERVER#
}

# run shiny ----
shinyApp(ui, server)
'
